dotenv: .env
wallets:
  from_key_1: ${PRIVATE_KEY_1}
  from_key_2: ${PRIVATE_KEY_2}
  from_key_dev_1: ${PRIVATE_KEY_DEV_1}
  from_key_dev_2: ${PRIVATE_KEY_DEV_2}
  from_key_dev_3: ${PRIVATE_KEY_DEV_3}
  from_key_dev_4: ${PRIVATE_KEY_DEV_4}
  from_key_dev_5: ${PRIVATE_KEY_DEV_5}
  from_key_dev_6: ${PRIVATE_KEY_DEV_6}
  from_key_dev_7: ${PRIVATE_KEY_DEV_7}
  from_key_dev_8: ${PRIVATE_KEY_DEV_8}
  from_key_dev_9: ${PRIVATE_KEY_DEV_9}
  from_key_dev_10: ${PRIVATE_KEY_DEV_10}
networks:
  sepolia:
    DAI: 0x3e622317f8C93f7328350cF0B56d9eD4C620C5d6
    
dependencies:
  - smartcontractkit/chainlink@2.2.0
  - OpenZeppelin/openzeppelin-contracts@4.9.2
compiler:
  solc:
    remappings: 
      - '@chainlink=smartcontractkit/chainlink@2.2.0'
      - '@openzeppelin=OpenZeppelin/openzeppelin-contracts@4.9.2'
